version: 1
disable_existing_loggers: true


formatters:
  standard:
    format: "%(asctime)s %(levelname)7s %(thread)5d --- [%(threadName)16s] %(funcName)-20s: %(message)s"
  colored_console:
    (): coloredlogs.ColoredFormatter
    fmt: "%(asctime)s.%(msecs)03d %(levelname)7s %(thread)5d --- [%(threadName)16s] %(funcName)-20s: %(message)s"
    field_styles: {'asctime': {'color': ''}, 'thread': {'color': 'magenta'}, 'funcName': {'color': 'cyan'}}


handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored_console
    stream: ext://sys.stdout


loggers:
  server:
    level: DEBUG
    handlers: [console]
    propogate: no

  speak:
    level: INFO
    handlers: [console]
    propogate: no

  move:
    level: INFO
    handlers: [console]
    propogate: no

  camera:
    level: DEBUG
    handlers: [console]
    propogate: no

  stream:
    level: DEBUG
    handlers: [console]
    propogate: no

  power_module:
    level: INFO
    handlers: [console]
    propogate: no

  servo:
    level: INFO
    handlers: [console]
    propogate: no

  led:
    level: INFO
    handlers: [console]
    propogate: no